<?php

/**
 * PluginReportLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginReportLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginReportLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginReportLog');
    }
}