<?php

/**
 * PluginModerationLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginModerationLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginModerationLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginModerationLog');
    }
}