all:
  moderation:
    javascript:          JQuery   # JQuery or MooTools version
    use_slots:           false
    audit:               false
    notify:
      #from: 
      #  name:           put these
      #  email:          into your app's app.yml
      subject:          "An item has been reported"
      # this can be a single email string, or an array of multiple emails:
      emails:         
